"""
waf_detector.py - Fingerprint WAF và đề xuất bypass strategy.
Chạy một lần đầu tiên trước tất cả các scan module.
"""
import httpx
from dataclasses import dataclass, field


@dataclass
class WAFResult:
    detected: bool
    waf_name: str
    confidence: float            # 0.0 - 1.0
    bypass_strategies: list[str] = field(default_factory=list)
    evidence: str = ""


class WAFDetector:
    """
    1. Gửi probe request với payload nguy hiểm → trigger WAF
    2. Fingerprint WAF từ headers, cookies, body, status code
    3. Trả về tên WAF + danh sách bypass strategy
    """

    # Signature per WAF: headers, cookies, body strings
    SIGNATURES: dict[str, dict] = {
        "Cloudflare": {
            "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
            "cookies": ["__cfduid", "cf_clearance", "__cf_bm"],
            "body":    ["cloudflare ray id", "cloudflare", "attention required"],
            "status":  [],
        },
        "AWS WAF": {
            "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-trace-id"],
            "cookies": [],
            "body":    ["aws waf", "request blocked"],
            "status":  [403],
        },
        "ModSecurity": {
            "headers": ["x-modsec", "x-mod-security"],
            "cookies": [],
            "body":    ["modsecurity", "mod_security", "this error was generated by mod_security", "not acceptable"],
            "status":  [406, 501],
        },
        "Akamai": {
            "headers": ["akamai-grn", "x-akamai-transformed", "x-check-cacheable"],
            "cookies": ["ak_bmsc", "bm_sz"],
            "body":    ["access denied - akamai", "reference #"],
            "status":  [],
        },
        "F5 BIG-IP ASM": {
            "headers": ["x-cnection", "x-wa-info"],
            "cookies": ["ts", "bigipserver", "f5_cspm"],
            "body":    ["the requested url was rejected", "please consult with your administrator"],
            "status":  [400],
        },
        "Imperva (Incapsula)": {
            "headers": ["x-iinfo", "x-cdn"],
            "cookies": ["incap_ses", "visid_incap", "_incap_"],
            "body":    ["incapsula incident id", "request unsuccessful"],
            "status":  [],
        },
        "Sucuri": {
            "headers": ["x-sucuri-id", "x-sucuri-cache"],
            "cookies": [],
            "body":    ["sucuri website firewall", "access denied - sucuri"],
            "status":  [403],
        },
    }

    BYPASS_STRATEGIES: dict[str, list[str]] = {
        "Cloudflare": [
            "URL double-encoding: %2527 thay vì %27",
            "Case variation: SeLeCt thay vì SELECT",
            "Unicode normalization: ＜script＞ (fullwidth chars)",
            "Chunked Transfer-Encoding bypass",
            "HTTP/2 request smuggling probe",
        ],
        "ModSecurity": [
            "Null byte injection: payload%00",
            "HTTP Parameter Pollution: ?id=1&id=PAYLOAD",
            "Multipart boundary obfuscation",
            "Whitespace alternative: SELECT%09FROM (TAB thay space)",
            "Comment injection: SEL/**/ECT",
        ],
        "AWS WAF": [
            "Hex encoding partial: %3c%73cript>",
            "URL double-encoding",
            "JSON body injection thay URL params",
            "Case variation kết hợp comment",
        ],
        "Akamai": [
            "SQL comment injection: OR/**/1=1",
            "Whitespace alternatives: %0a, %0d",
            "Encoding bypass với charset tricks",
        ],
        "Unknown": [
            "URL double-encoding: %2527",
            "SQL comment: SEL/**/ECT",
            "Case variation: SeLeCt",
            "Whitespace: %09 (TAB), %0a (newline)",
            "Null byte: payload%00",
        ],
    }

    # Probe payload - đủ nguy hiểm để trigger WAF nhưng không gây hại
    PROBE_SUFFIX = "?__waf_test=<script>alert(1)</script>&id=1'%20OR%201=1--"

    async def detect(self, base_url: str, client: httpx.AsyncClient) -> WAFResult:
        probe_url = base_url.rstrip("/") + self.PROBE_SUFFIX
        try:
            resp = await client.get(probe_url)
        except httpx.TimeoutException:
            # Timeout sau probe = có thể WAF đang block silently
            return WAFResult(
                detected=True,
                waf_name="Unknown (silent block)",
                confidence=0.5,
                bypass_strategies=self.BYPASS_STRATEGIES["Unknown"],
                evidence="Request timed out after WAF probe",
            )
        except Exception as e:
            return WAFResult(detected=False, waf_name="None", confidence=0.0,
                           evidence=f"Probe error: {e}")

        waf_name, confidence, evidence = self._fingerprint(resp)
        bypass = self.BYPASS_STRATEGIES.get(waf_name, self.BYPASS_STRATEGIES["Unknown"])

        return WAFResult(
            detected=confidence >= 0.4,
            waf_name=waf_name if confidence >= 0.4 else "None detected",
            confidence=round(confidence, 2),
            bypass_strategies=bypass if confidence >= 0.4 else [],
            evidence=evidence,
        )

    def _fingerprint(self, resp: httpx.Response) -> tuple[str, float, str]:
        headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}
        cookies_lower = {k.lower(): v.lower() for k, v in resp.cookies.items()}
        body_lower = resp.text.lower()[:3000]
        status = resp.status_code

        best_waf = "Unknown"
        best_score = 0.0
        best_evidence = []

        for waf_name, sigs in self.SIGNATURES.items():
            hits = []
            total_signals = 0

            for h in sigs["headers"]:
                total_signals += 1
                if h in headers_lower:
                    hits.append(f"header:{h}")

            for c in sigs["cookies"]:
                total_signals += 1
                if any(c in ck for ck in cookies_lower):
                    hits.append(f"cookie:{c}")

            for b in sigs["body"]:
                total_signals += 1
                if b in body_lower:
                    hits.append(f"body:'{b}'")

            for s in sigs["status"]:
                total_signals += 1
                if status == s:
                    hits.append(f"status:{s}")

            if total_signals > 0 and hits:
                score = len(hits) / total_signals
                # Body + header combo = higher confidence
                if any("body:" in h for h in hits) and any("header:" in h or "cookie:" in h for h in hits):
                    score = min(score * 1.5, 1.0)
                if score > best_score:
                    best_score = score
                    best_waf = waf_name
                    best_evidence = hits

        evidence_str = ", ".join(best_evidence) if best_evidence else f"HTTP {status}, no signature match"
        return best_waf, best_score, evidence_str